#include "zinc/io/poscar.h"
#include <fstream>
#include <sstream>
#include <stdexcept>
#include <cmath>
#include <iomanip>
#include <algorithm>
#include <array>

namespace zinc {
namespace io {

bool PoscarDriver::identify(const std::string& first_line) const {
  std::istringstream hss(first_line);
  std::string title, scale_line;
  std::getline(hss, title);
  if (!std::getline(hss, scale_line)) return false;
  std::istringstream sss(scale_line);
  double scale;
  if (!(sss >> scale)) return false;
  std::string l1, l2, l3;
  if (!std::getline(hss, l1) || !std::getline(hss, l2) || !std::getline(hss, l3)) return false;
  return true;
}

core::Structure PoscarDriver::read(const std::filesystem::path& path) const {
  std::ifstream file(path);
  if (!file.is_open()) throw std::runtime_error("Cannot open: " + path.string());

  std::string line;
  std::getline(file, line);
  std::getline(file, line);
  double scale = std::stod(line);

  auto parse_vec = [&file]() -> core::Vector3d {
    std::string l; std::getline(file, l);
    std::istringstream ss(l); double x, y, z; ss >> x >> y >> z;
    return core::Vector3d(x, y, z);
  };

  core::Vector3d v1 = parse_vec() * scale;
  core::Vector3d v2 = parse_vec() * scale;
  core::Vector3d v3 = parse_vec() * scale;
  core::Lattice lattice(v1, v2, v3);
  core::Structure structure(lattice);

  std::getline(file, line);
  std::vector<std::string> symbols;
  std::vector<int> counts;

  auto is_number_line = [](const std::string& s) -> bool {
    std::istringstream ts(s);
    std::string tok;
    while (ts >> tok) {
      try { std::stoi(tok); } catch (...) { return false; }
    }
    return true;
  };

  if (is_number_line(line)) {
    // VASP4: only counts, no symbols
    std::istringstream ss(line);
    std::string token;
    while (ss >> token) counts.push_back(std::stoi(token));
    char c = 'A';
    for (size_t i = 0; i < counts.size(); ++i) symbols.push_back(std::string(1, c++));
  } else {
    // VASP5: symbols then counts
    std::istringstream ss(line);
    std::string token;
    while (ss >> token) symbols.push_back(token);
    std::getline(file, line);
    std::istringstream css(line);
    while (css >> token) counts.push_back(std::stoi(token));
  }

  std::getline(file, line);
  bool selective = (line.find("Selective") != std::string::npos);
  if (selective) std::getline(file, line);

  bool frac = (line.find("Direct") != std::string::npos || line.find("direct") != std::string::npos ||
               line.rfind("D", 0) == 0 || line.rfind("d", 0) == 0 ||
               line.rfind("K", 0) == 0 || line.rfind("k", 0) == 0);

  int total = 0; for (int c : counts) total += c;
  int idx = 0;
  for (int i = 0; i < total; ++i) {
    std::getline(file, line);
    std::istringstream ass(line); double x, y, z; ass >> x >> y >> z;
    core::Vector3d pos(x, y, z);
    if (frac) pos = lattice.frac_to_cart(pos);

    std::string elem = "X";
    int k = idx;
    for (size_t s = 0; s < symbols.size(); ++s) {
      if (k < counts[s]) { elem = symbols[s]; break; }
      k -= counts[s];
    }
    idx++;

    std::optional<std::array<int, 3>> constr;
    if (selective) {
      std::string t1, t2, t3;
      ass >> t1 >> t2 >> t3;
      auto tf = [](const std::string& s) -> int {
        return (s == "F" || s == "f") ? 0 : 1;
      };
      constr = std::array<int, 3>{tf(t1), tf(t2), tf(t3)};
    }
    structure.add_atom(elem, {pos.x(), pos.y(), pos.z()}, constr);
  }
  return structure;
}

void PoscarDriver::write(const core::Structure& structure, const std::filesystem::path& path) const {
  std::ofstream out(path);
  if (!out.is_open()) throw std::runtime_error("Cannot open output file: " + path.string());
  out << std::fixed << std::setprecision(10);
  out << "Generated by zinc\n1.0\n";
  const auto& mat = structure.lattice.matrix();
  for (int i = 0; i < 3; ++i)
    out << std::setw(18) << mat(i,0)
        << std::setw(18) << mat(i,1)
        << std::setw(18) << mat(i,2) << "\n";

  std::vector<std::string> elems; std::vector<int> counts;
  for (const auto& atom : structure.atoms) {
    bool f = false;
    for (size_t i = 0; i < elems.size(); ++i) {
      if (elems[i] == atom.element) { counts[i]++; f = true; break; }
    }
    if (!f) { elems.push_back(atom.element); counts.push_back(1); }
  }
  for (const auto& e : elems) out << e << " "; out << "\n";
  for (int c : counts) out << c << " "; out << "\n";

  bool has_fixed_atom = std::any_of(structure.atoms.begin(), structure.atoms.end(),
                                    [](const auto& a) {
                                      return a.constraints && ((*a.constraints)[0] == 0 ||
                                                               (*a.constraints)[1] == 0 ||
                                                               (*a.constraints)[2] == 0);
                                    });
  if (has_fixed_atom) out << "Selective dynamics\n";
  out << "Cartesian\n";

  for (const auto& atom : structure.atoms) {
    out << std::setw(18) << atom.position.x()
        << std::setw(18) << atom.position.y()
        << std::setw(18) << atom.position.z();
    if (has_fixed_atom) {
      const auto c = atom.constraints.value_or(std::array<int, 3>{1, 1, 1});
      out << "  " << (c[0] ? "T" : "F") << "  " << (c[1] ? "T" : "F") << "  " << (c[2] ? "T" : "F");
    }
    out << "\n";
  }
}

} // namespace io
} // namespace zinc
